/**
 * Camera Export Service
 * Exports camera data to After Effects and generic JSON formats
 *
 * NOTE: For AI video model exports (Uni3C, MotionCtrl, CameraCtrl, etc.),
 * use the functions in services/export/cameraExportFormats.ts instead.
 */

import type { Camera3D, CameraKeyframe } from '../types/camera';

/**
 * Export camera to JSON file (generic format for backup/import)
 */
export function exportCameraJSON(
  camera: Camera3D,
  keyframes: CameraKeyframe[]
): string {
  return JSON.stringify({
    camera,
    keyframes,
    exportedAt: new Date().toISOString(),
    version: '1.0'
  }, null, 2);
}

/**
 * Import camera from JSON
 */
export function importCameraJSON(json: string): { camera: Camera3D; keyframes: CameraKeyframe[] } | null {
  try {
    const data = JSON.parse(json);
    if (data.camera && data.keyframes) {
      return {
        camera: data.camera,
        keyframes: data.keyframes
      };
    }
    return null;
  } catch {
    return null;
  }
}

/**
 * Export to After Effects camera format (ExtendScript compatible)
 */
export function exportToAEScript(
  camera: Camera3D,
  keyframes: CameraKeyframe[],
  compName: string
): string {
  let script = `// After Effects Camera Import Script
// Generated by Lattice Compositor
// Camera: ${camera.name}

(function() {
  var comp = app.project.activeItem;
  if (!(comp instanceof CompItem)) {
    alert("Please select a composition first.");
    return;
  }

  var camera = comp.layers.addCamera("${camera.name}", [comp.width/2, comp.height/2]);
  var cameraOptions = camera.property("ADBE Camera Options Group");

  // Set camera type
  camera.property("ADBE Camera Options Group").property("ADBE Camera Type").setValue(${camera.type === 'two-node' ? 2 : 1});

  // Set initial position
  camera.position.setValue([${camera.position.x}, ${camera.position.y}, ${camera.position.z}]);

`;

  if (camera.type === 'two-node') {
    script += `  // Set point of interest
  camera.pointOfInterest.setValue([${camera.pointOfInterest.x}, ${camera.pointOfInterest.y}, ${camera.pointOfInterest.z}]);

`;
  }

  script += `  // Set zoom (focal length)
  cameraOptions.property("ADBE Camera Zoom").setValue(${camera.zoom});

  // Set depth of field
  cameraOptions.property("ADBE Camera Depth of Field").setValue(${camera.depthOfField.enabled ? 1 : 0});
  cameraOptions.property("ADBE Camera Focus Distance").setValue(${camera.depthOfField.focusDistance});
  cameraOptions.property("ADBE Camera Aperture").setValue(${camera.depthOfField.aperture});
  cameraOptions.property("ADBE Camera Blur Level").setValue(${camera.depthOfField.blurLevel * 100});

`;

  // Add keyframes if present
  if (keyframes.length > 0) {
    script += `  // Add keyframes
`;
    for (const kf of keyframes) {
      const frameTime = kf.frame / 30; // Assuming 30fps
      if (kf.position) {
        script += `  camera.position.setValueAtTime(${frameTime}, [${kf.position.x}, ${kf.position.y}, ${kf.position.z}]);
`;
      }
      if (kf.pointOfInterest) {
        script += `  camera.pointOfInterest.setValueAtTime(${frameTime}, [${kf.pointOfInterest.x}, ${kf.pointOfInterest.y}, ${kf.pointOfInterest.z}]);
`;
      }
      if (kf.zoom !== undefined) {
        script += `  cameraOptions.property("ADBE Camera Zoom").setValueAtTime(${frameTime}, ${kf.zoom});
`;
      }
    }
  }

  script += `
  alert("Camera '${camera.name}' created successfully!");
})();
`;

  return script;
}

/**
 * Download file helper
 */
export function downloadFile(content: string, filename: string, mimeType: string = 'application/json') {
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}
