/**
 * Layer Schema Exports
 *
 * Re-exports all layer-related Zod schemas.
 */

// Primitives
export {
  finiteNumber,
  positiveFinite,
  nonNegativeFinite,
  normalized01,
  normalizedNeg1To1,
  positiveInt,
  nonNegativeInt,
  frameNumber,
  Vec2Schema,
  Vec3Schema,
  Position2DOr3DSchema,
  RGBAColorSchema,
  RGBA255ColorSchema,
  HexColorSchema,
  ColorValueSchema,
  RectSchema,
  EntityIdSchema,
  NullableEntityIdSchema,
  BlendModeSchema,
  QualityModeSchema,
  type Vec2,
  type Vec3,
  type Position2DOr3D,
  type RGBAColor,
  type RGBA255Color,
  type HexColor,
  type ColorValue,
  type Rect,
  type EntityId,
  type NullableEntityId,
  type BlendMode,
  type QualityMode,
} from "./primitives-schema";

// Animation
export {
  BaseInterpolationTypeSchema,
  EasingTypeSchema,
  InterpolationTypeSchema,
  BezierHandleSchema,
  ControlModeSchema,
  PropertyValueSchema,
  KeyframeSchema,
  NumberKeyframeSchema,
  PositionKeyframeSchema,
  ColorKeyframeSchema,
  PropertyExpressionSchema,
  PropertyTypeSchema,
  createAnimatablePropertySchema,
  AnimatableNumberSchema,
  AnimatablePositionSchema,
  AnimatableVec3Schema,
  AnimatableColorSchema,
  AnimatableEnumSchema,
  AnimatablePropertySchema,
  ClipboardKeyframeSchema,
  type BaseInterpolationType,
  type EasingType,
  type InterpolationType,
  type BezierHandle,
  type ControlMode,
  type PropertyValue,
  type Keyframe,
  type NumberKeyframe,
  type PositionKeyframe,
  type ColorKeyframe,
  type PropertyExpression,
  type PropertyType,
  type AnimatableNumber,
  type AnimatablePosition,
  type AnimatableVec3,
  type AnimatableColor,
  type AnimatableEnum,
  type AnimatableProperty,
  type ClipboardKeyframe,
} from "./animation-schema";

// Transform
export {
  SeparateDimensionsSchema,
  LayerTransformSchema,
  MotionBlurTypeSchema,
  LayerMotionBlurSettingsSchema,
  LayerMaterialOptionsSchema,
  AutoOrientModeSchema,
  FollowPathConstraintSchema,
  AudioPathAnimationSchema,
  type SeparateDimensions,
  type LayerTransform,
  type MotionBlurType,
  type LayerMotionBlurSettings,
  type LayerMaterialOptions,
  type AutoOrientMode,
  type FollowPathConstraint,
  type AudioPathAnimation,
} from "./transform-schema";

// Layer Data
export {
  ImageFitModeSchema,
  ImageLayerDataSchema,
  VideoDataSchema,
  DepthVisualizationModeSchema,
  DepthColorMapSchema,
  DepthLayerDataSchema,
  NormalVisualizationModeSchema,
  NormalLayerDataSchema,
  AudioMarkerSchema,
  AudioLayerDataSchema,
  GenerationTypeSchema,
  GeneratedLayerDataSchema,
  SolidLayerDataSchema,
  ControlLayerDataSchema,
  NullLayerDataSchema,
  GroupLayerDataSchema,
  EffectLayerDataSchema,
  NestedCompDataSchema,
  CameraTypeSchema,
  DepthOfFieldSchema,
  IrisSchema,
  HighlightSchema,
  CameraLayerDataSchema,
  LightTypeSchema,
  LightLayerDataSchema,
  PoseKeypointSchema,
  PoseSchema,
  PoseLayerDataSchema,
  ModelLayerDataSchema,
  PointCloudLayerDataSchema,
  MatteTypeEnumSchema,
  MatteLayerDataSchema,
  ProceduralMatteDataSchema,
  DepthflowLayerDataSchema,
  GeneratedMapDataSchema,
  ControlPointTypeSchema,
  HandleSchema,
  ControlPointSchema,
  RGBAColorObjectSchema,
  GradientStopSchema,
  StrokeGradientSchema,
  SplineDataSchema,
  PathLayerDataSchema,
  TextAlignSchema,
  TextBaselineSchema,
  TextDirectionSchema,
  TextDataSchema,
  ShapeLayerDataSchema,
  EmitterShapeSchema,
  LegacyParticleLayerDataSchema,
  ParticleLayerDataSchema,
  LayerDataSchema,
  type ImageLayerData,
  type VideoData,
  type DepthLayerData,
  type NormalLayerData,
  type AudioLayerData,
  type GeneratedLayerData,
  type SolidLayerData,
  type ControlLayerData,
  type NullLayerData,
  type GroupLayerData,
  type EffectLayerData,
  type NestedCompData,
  type CameraLayerData,
  type LightLayerData,
  type PoseLayerData,
  type ModelLayerData,
  type PointCloudLayerData,
  type MatteLayerData,
  type ProceduralMatteData,
  type DepthflowLayerData,
  type GeneratedMapData,
  type ControlPoint,
  type SplineData,
  type PathLayerData,
  type TextData,
  type ShapeLayerData,
  type LegacyParticleLayerData,
  type ParticleLayerData,
  type LayerData,
} from "./layer-data-schema";

// Main Layer
export {
  LayerTypeSchema,
  MatteTypeSchema,
  EffectInstanceSchema,
  MaskModeSchema,
  LayerMaskSchema,
  LayerStylesSchema,
  LayerAudioSchema,
  LayerSchema,
  validateLayer,
  safeValidateLayer,
  type LayerType,
  type MatteType,
  type EffectInstance,
  type LayerMask,
  type LayerStyles,
  type LayerAudio,
  type Layer,
} from "./layer-schema";
