import Compass.Core
import Compass.Auth
import Compass.Router
import Compass.Budget
import Compass.BudgetState
import Compass.RateLimiter
import Compass.Flags

namespace Compass.TestMain

open Compass.Core
open Compass.Auth
open Compass.Router
open Compass.Budget
open Compass.BudgetState
open Compass.RateLimiter

/-! ## Test Case Generation -/

/-- Generate test cases for authentication invariants -/
def authTestCases : List String :=
  [
    "-- Session MFA requirement",
    "@given(st.builds(Session, mfa_verified=st.booleans()))",
    "def test_session_mfa_requirement(s):",
    "    assume(s.mfa_verified == True)",
    "    assert s.isValid",
    "",
    "-- API key prefix validation",
    "@given(st.text(min_size=8, max_size=8))",
    "def test_apikey_prefix_validation(prefix):",
    "    key = APIKey(key_prefix=prefix, ...)",
    "    if key.prefixValid:",
    "        assert key.key_prefix.startswith('flk_')",
    "",
    "-- User invariants",
    "@given(st.builds(User))",
    "def test_user_invariants(u):",
    "    assert len(u.email) > 0 and '@' in u['email']",
    "    assert len(u.id) > 0"
  ]

/-- Generate test cases for router security -/
def routerTestCases : List String :=
  [
    "-- API key scope restriction",
    "@given(st.lists(st.sampled_from(Operation), min_size=1), st.sampled_from(Operation))",
    "def test_scope_restriction(allowed_ops, op):",
    "    scope = Scope(allowedOps=allowed_ops)",
    "    if op in allowed_ops:",
    "        assert restricts(scope, op)",
    "",
    "-- Circuit breaker state",
    "@given(st.sampled_from(['closed', 'open', 'half_open']))",
    "def test_circuit_breaker_state(state):",
    "    cb = CircuitBreaker(state=state, ...)",
    "    if state == 'closed':",
    "        assert cb.allowsRequest == True",
    "    elif state == 'open':",
    "        assert cb.allowsRequest == False",
    "",
    "-- Privilege escalation prevention",
    "@given(st.lists(st.sampled_from(Operation)), st.lists(st.sampled_from(Operation)))",
    "def test_privilege_escalation(base_ops, derived_ops):",
    "    assume(set(derived_ops).issubset(set(base_ops)))",
    "    base = Scope(allowedOps=base_ops)",
    "    derived = Scope(allowedOps=derived_ops)",
    "    for op in Operation:",
    "        if not restricts(base, op):",
    "            assert not restricts(derived, op)"
  ]

/-- Generate test cases for budget control -/
def budgetTestCases : List String :=
  [
    "-- Budget refill monotonicity",
    "@given(st.builds(BudgetState), st.integers(min_value=0, max_value=100))",
    "def test_budget_refill_monotonic(bs, amt):",
    "    refilled = refill(bs, amt)",
    "    assert refilled.current >= bs.current",
    "    assert refilled.current <= refilled.max",
    "",
    "-- Budget consumption atomicity",
    "@given(st.builds(BudgetState), st.integers(min_value=0, max_value=50))",
    "def test_budget_consumption_atomic(bs, amt):",
    "    result = consume(bs, amt)",
    "    if bs.current >= amt:",
    "        assert result is not None",
    "        assert result.current == bs.current - amt",
    "    else:",
    "        assert result is None"
  ]

/-- Generate test cases for rate limiting -/
def rateLimitTestCases : List String :=
  [
    "-- Token bucket capacity bounds",
    "@given(st.builds(Bucket))",
    "def test_bucket_bounds(bucket):",
    "    assert 0 <= bucket.current <= bucket.capacity",
    "",
    "-- Bucket consumption",
    "@given(st.builds(Bucket), st.integers(min_value=1, max_value=10))",
    "def test_bucket_consume(bucket, amt):",
    "    result = tryConsume(bucket, amt)",
    "    if bucket.current >= amt:",
    "        assert result is not None",
    "        assert result.current == bucket.current - amt",
    "    else:",
    "        assert result is None"
  ]

/-- Generate Python Hypothesis test file -/
def generatePythonTests : String :=
  let header := "# Generated by Lean4 - DO NOT EDIT MANUALLY
import hypothesis
from hypothesis import strategies as st, given, assume
import pytest

# Import generated COMPASS types
from compass_types import *

"
  let authTests := String.join (authTestCases.map (λ s => s ++ "\n"))
  let routerTests := String.join (routerTestCases.map (λ s => s ++ "\n"))
  let budgetTests := String.join (budgetTestCases.map (λ s => s ++ "\n"))
  let rateTests := String.join (rateLimitTestCases.map (λ s => s ++ "\n"))

  header ++
  "# Authentication Tests\n" ++ authTests ++ "\n" ++
  "# Router Security Tests\n" ++ routerTests ++ "\n" ++
  "# Budget Control Tests\n" ++ budgetTests ++ "\n" ++
  "# Rate Limiting Tests\n" ++ rateTests

/-- Main test generation function -/
def main : IO Unit := do
  let pythonTests := generatePythonTests

  -- Write Python test file
  IO.FS.writeFile "tests/generated_security_tests.py" pythonTests

  IO.println "Generated security test suite"
  IO.println "Python tests: tests/generated_security_tests.py"

end Compass.TestMain
