"""Type stub for ComfyUI folder_paths module."""

models_dir: str
input_dir: str
output_dir: str
temp_dir: str


def get_output_directory() -> str: ...
def get_input_directory() -> str: ...
def get_temp_directory() -> str: ...
def get_user_directory() -> str: ...
def get_folder_paths(folder_name: str) -> list[str]:
    """Get folder paths for the specified folder name."""
    ...
