/**
 * Export Schema Index
 *
 * Zod schemas for validating export data formats.
 * These define the contract between TypeScript and Python ComfyUI nodes.
 */

export {
  CameraExportOutputSchema,
  CameraFormatSchema,
  CameraFrameSchema,
  CameraIntrinsicsSchema,
  CoordinateSystemSchema,
  Matrix4x4Schema,
  MotionCtrlOutputSchema,
  safeValidateCameraOutput,
  validateCameraOutput,
  WanMoveOutputSchema,
  type CameraExportOutput,
  type CameraFormat,
  type CameraFrame,
  type CameraIntrinsics,
  type CoordinateSystem,
  type Matrix4x4,
} from "./camera-schema";

export {
  ColormapSchema,
  DepthExportOutputSchema,
  DepthFormatSchema,
  DepthFrameOutputSchema,
  DepthRangeSchema,
  safeValidateDepthOutput,
  validateDepthOutput,
  type Colormap,
  type DepthExportOutput,
  type DepthFormat,
  type DepthFrameOutput,
  type DepthRange,
} from "./depth-schema";

// ATI Export Schemas
export {
  ATI_FIXED_FRAMES,
  ATI_MAX_DIMENSION,
  ATI_MIN_DIMENSION,
  ATITrackPointSchema,
  ATIPointTupleSchema,
  ATITrackFramesSchema,
  ATITracksArraySchema,
  ATIVisibilitySchema,
  ATIExportResultSchema,
  ATIExportConfigSchema,
  ATITracksImportSchema,
  ATIDataSchema,
  type ATITrackPoint,
  type ATIPointTuple,
  type ATITrackFrames,
  type ATITracksArray,
  type ATIVisibility,
  type ATIExportResult,
  type ATIExportConfig,
  type ATIData,
} from "./ati-schema";

// WanMove Export Schemas
export {
  WANMOVE_MAX_DIMENSION,
  WANMOVE_MAX_POINTS,
  WANMOVE_MAX_FRAMES,
  Point2DSchema,
  TrackPointTupleSchema,
  // Note: TrackPointSchema is exported from workflow-params-schema.ts (line 315) - same schema, avoid duplicate
  RGBColorTupleSchema,
  WanMoveMetadataSchema,
  SingleTrackSchema,
  TracksArraySchema,
  SingleVisibilitySchema,
  VisibilityArraySchema,
  WanMoveTrajectorySchema,
  ColorStopSchema,
  ColorGradientSchema,
  ColoredTrajectorySchema,
  FlowPatternSchema,
  MorphShapeTypeSchema,
  MorphEasingSchema,
  ShapeEasingSchema,
  GenerativeFlowParamsSchema,
  GenerativeFlowConfigSchema,
  DataMappingSchema,
  SplinePointSchema,
  DataDrivenFlowConfigSchema,
  AttractorTypeSchema,
  AttractorConfigSchema,
  CircleShapeSchema,
  GridShapeSchema,
  TextShapeSchema,
  HeartShapeSchema,
  StarShapeSchema,
  SpiralShapeSchema,
  RandomShapeSchema,
  CustomShapeSchema,
  ShapeDefinitionSchema,
  ShapeTargetConfigSchema,
  ForceFalloffSchema,
  ForcePointSchema,
  InitialDistributionSchema,
  ForceFieldConfigSchema,
  FlowLayerSchema,
  RenderOptionsSchema,
  WanMoveExportPackageSchema,
  WanMoveDataSchema,
  type Point2D,
  type TrackPointTuple,
  // Note: type TrackPoint exported from workflow-params-schema.ts (line 324) - same type, avoid duplicate
  type RGBColorTuple,
  type WanMoveMetadata,
  type SingleTrack,
  type TracksArray,
  type SingleVisibility,
  type VisibilityArray,
  type WanMoveTrajectory,
  type ColorStop,
  type ColorGradient,
  type ColoredTrajectory,
  type FlowPattern,
  type MorphShapeType,
  type MorphEasing,
  type ShapeEasing,
  type GenerativeFlowParams,
  type GenerativeFlowConfig,
  type DataMapping,
  type SplinePoint,
  type DataDrivenFlowConfig,
  type AttractorType,
  type AttractorConfig,
  type ShapeDefinition,
  type ShapeTargetConfig,
  type ForceFalloff,
  type ForcePoint,
  type InitialDistribution,
  type ForceFieldConfig,
  type FlowLayer,
  type RenderOptions,
  type WanMoveExportPackage,
  type WanMoveData,
} from "./wanmove-schema";

// ControlNet Export Schemas
export {
  ControlNetTypeSchema,
  ControlNetExportConfigSchema,
  OpenPosePersonSchema,
  OpenPoseJSONSchema,
  PoseExportConfigSchema,
  PoseSequenceMetadataSchema,
  PoseSequenceJsonSchema,
  PoseExportResultSchema,
  ControlNetExportResultSchema,
  validateOpenPoseJSON,
  safeValidateOpenPoseJSON,
  validatePoseExportResult,
  safeValidatePoseExportResult,
  type ControlNetType,
  type ControlNetExportConfig,
  type OpenPosePerson,
  type OpenPoseJSON,
  type PoseExportConfig,
  type PoseSequenceMetadata,
  type PoseSequenceJson,
  type PoseExportResult,
  type ControlNetExportResult,
} from "./controlnet-schema";

// Normal Map Export Schemas
export {
  NormalGenerationMethodSchema,
  NormalDepthModelSchema,
  NormalGenerationOptionsSchema,
  NormalGenerationMetadataSchema,
  NormalGenerationResultSchema,
  validateNormalGenerationResult,
  safeValidateNormalGenerationResult,
  type NormalGenerationMethod,
  type NormalDepthModel,
  type NormalGenerationOptions,
  type NormalGenerationMetadata,
  type NormalGenerationResult,
} from "./normal-schema";

// TTM Export Schemas
export {
  TTMModelSchema,
  TTMLayerExportSchema,
  TTMModelConfigSchema,
  TTMMetadataSchema,
  TTMExportSchema,
  TTMSingleLayerExportSchema,
  validateTTMExport,
  safeValidateTTMExport,
  type TTMModel,
  type TTMLayerExport,
  type TTMModelConfig,
  type TTMMetadata,
  type TTMExport,
  type TTMSingleLayerExport,
} from "./ttm-schema";

// Light-X Export Schemas
export {
  LightXMotionStyleSchema,
  LightXRelightSourceSchema,
  CameraTrajectoryExportSchema,
  LightXRelightingConfigSchema,
  LightXExportSchema,
  validateLightXExport,
  safeValidateLightXExport,
  type LightXMotionStyle,
  type LightXRelightSource,
  type CameraTrajectoryExport,
  type LightXRelightingConfig,
  type LightXExport,
} from "./lightx-schema";

// Mesh Deform Export Schemas
export {
  CompositionInfoSchema,
  PinMetadataSchema,
  PinTrajectoryExportSchema,
  MeshDeformDepthFormatSchema,
  MeshMaskExportMetadataSchema,
  OverlapDepthExportMetadataSchema,
  MeshMaskSequenceExportSchema,
  OverlapDepthSequenceExportSchema,
  validatePinTrajectoryExport,
  safeValidatePinTrajectoryExport,
  type CompositionInfo,
  type PinMetadata,
  type PinTrajectoryExport,
  type MeshDeformDepthFormat,
  type MeshMaskExportMetadata,
  type OverlapDepthExportMetadata,
  type MeshMaskSequenceExport,
  type OverlapDepthSequenceExport,
} from "./meshdeform-schema";

// VACE Export Schemas
export {
  PathFollowerShapeSchema,
  PathFollowerEasingSchema,
  SplineControlPointSchema,
  PathFollowerConfigSchema,
  VACEExportConfigSchema,
  PathFollowerStateSchema,
  VACEFrameMetadataSchema,
  validateVACEExportConfig,
  safeValidateVACEExportConfig,
  type PathFollowerShape,
  type PathFollowerEasing,
  type SplineControlPoint,
  type PathFollowerConfig,
  type VACEExportConfig,
  type PathFollowerState,
  type VACEFrameMetadata,
} from "./vace-schema";

// Particle Trajectory Export Schemas
export {
  ParticlePositionSchema,
  ParticleVelocitySchema,
  ParticleColorSchema,
  ParticleDataSchema,
  EmitterConfigSchema,
  ParticleTrajectoryExportSchema,
  validateParticleTrajectoryExport,
  safeValidateParticleTrajectoryExport,
  type ParticlePosition,
  type ParticleVelocity,
  type ParticleColor,
  type ParticleData,
  type EmitterConfig,
  type ParticleTrajectoryExport,
} from "./particle-schema";

// Frame Sequence Export Schemas
export {
  FrameFormatSchema,
  ColorSpaceSchema,
  BitDepthSchema,
  FrameExportOptionsSchema,
  ExportedFrameSchema,
  FrameSequenceResultSchema,
  validateFrameSequenceResult,
  safeValidateFrameSequenceResult,
  type FrameFormat,
  type ColorSpace,
  type BitDepth,
  type FrameExportOptions,
  type ExportedFrame,
  type FrameSequenceResult,
} from "./framesequence-schema";

// SCAIL Export Schemas
export {
  SCAILExportConfigSchema,
  SCAILExportResultSchema,
  validateSCAILExportConfig,
  safeValidateSCAILExportConfig,
  type SCAILExportConfig,
  type SCAILExportResult,
} from "./scail-schema";

// WorkflowParams MotionData Schemas
export {
  TrackPointSchema,
  WanMoveMotionDataSchema,
  ATIMotionDataSchema,
  MotionDataSchema,
  validateWanMoveMotionData,
  safeValidateWanMoveMotionData,
  validateATIMotionData,
  safeValidateATIMotionData,
  validateMotionDataForTarget,
  type TrackPoint,
  type WanMoveMotionData,
  type ATIMotionData,
  type MotionData,
} from "./workflow-params-schema";
