/* ValueTransferrerVisualizer.h
 *
 * Peter Synak, Chris Wojtan, Huidong Yang, Aleksei Kalinov, Malina Strugaru, 2022
 *
 * This is the header file for value transfer visualizer.
 */

#pragma once

//------------------------------------------------------------
// includes
//------------------------------------------------------------

#include "../datastructures/Grid3DInterface.h"
#include "../submodules/ValueTransferrer.h"
#include "../utilities/vec.h"
#include "Visualizer.h"
#include "GridLabelerVisualizer.h"

//------------------------------------------------------------
// classes
//------------------------------------------------------------

class ValueTransferrerVisualizer : public Visualizer {
	friend ImGUIWindows;

 public:
	ValueTransferrerVisualizer();
	~ValueTransferrerVisualizer();

	// Initialize value transfer rendering.
	virtual void init(SDTopoFixer* topofixer, std::vector<Vec4d> colors) override;

	// Call private functions that render elements related to value transfer. See function
	// implementation for descriptions of rendering states.
	virtual void display() override;

	// Switch to the next rendering state.
	virtual void nextState() override;

 private:
	// Render initial velocity vectors on value giving mesh vertices in pink, i.e., the displayed
	// values were read from the input file.
	void renderInitialVelocitiesOnMesh();

	// Render interpolated velocity vectors on grid vertices, pink for those that had values
	// assigned onto them directly by interpolation from mesh vertices, blue for those that had
	// values assigned onto them by spreading vlaues through the grid.
	void renderVelocitiesOnGrid();

	// Render new velocity vectors on value taking mesh vertices in blue, i.e., the displayed values
	// were interpolated onto mesh vertices from grid vertices.
	void renderNewVelocitiesOnGridMesh();

	// Render velocity vectors on all mesh vertices in different colors:
	// -pink for original mesh vertices whose values didn't change;
	// -orange for original mesh vertices whose values changed;
	// -blue for mesh vertices generated by marching cubes;
	// -yellow for front face mesh vertices.
	void renderVelocitiesOnMeshBasedOnOrigin();

	// Render value giving mesh vertices in green.
	void renderValueGivingMeshVertices();

	// Render grid cells that contain at least one value giving mesh vertex, that is, all cells whose
	// vertices had values interpolated onto them.
	void renderInterpolationGridCells();

	// Render thickness values as small balls around vertices
	void renderThicknessesOnMesh();

	// Prints the description of the current rendering state state.
	void printDescription();

	// Render the line representing the `velocity` starting at `origin`.
	void renderVelocity(Vec3d origin, Vec3d velocity);

	// Render a small cube representing the 'thickness' starting at 'coords'.
	// Colors red, white, and blue represent the min, default, and max thicknesses respectively.
	void renderThickness(Vec3d coords, double thickness);

	//-------------------- data members

	Grid3DInterface* grid_;
	Mesh3DInterface* mesh_;
	ValueTransferrer* value_transferrer_;
	std::vector<Vec4d> velocity_colors_;
	GLfloat stored_line_width, stored_point_size;

	// Used to adjust the magnitude of visualised velocities.
	float velocity_scale_ = 1.0;

	// Parameters to track current draw state.
	unsigned int current_state_;
	const unsigned int kMaxStates = 7;
};