/**
 * AI Schema Exports
 */

export {
  ControlPointSchema,
  CameraMotionTypeSchema,
  MotionIntensitySchema,
  EasingTypeSchema,
  CameraMotionIntentSchema,
  SplineUsageSchema,
  SplineMotionIntentSchema,
  ParticleBehaviorSchema,
  ParticleMotionIntentSchema,
  LayerMotionTypeSchema,
  LayerMotionIntentSchema,
  MotionIntentResultSchema,
  MotionSuggestionSchema,
  validateMotionIntentResult,
  safeValidateMotionIntentResult,
  validateMotionSuggestion,
  safeValidateMotionSuggestion,
  type ControlPoint,
  type CameraMotionType,
  type MotionIntensity,
  type EasingType,
  type CameraMotionIntent,
  type SplineUsage,
  type SplineMotionIntent,
  type ParticleBehavior,
  type ParticleMotionIntent,
  type LayerMotionType,
  type LayerMotionIntent,
  type MotionIntentResult,
  type MotionSuggestion,
} from "./motion-suggestion-schema";
