export const abs = Math.abs;
export const acos = Math.acos;
export const asin = Math.asin;
export const atan = Math.atan;
export const atan2 = (y) => (x) => Math.atan2(y, x);
export const ceil = Math.ceil;
export const cos = Math.cos;
export const exp = Math.exp;
export const floor = Math.floor;
export const log = Math.log;
export const max = (a) => (b) => Math.max(a, b);
export const min = (a) => (b) => Math.min(a, b);
export const pow = (base) => (exponent) => Math.pow(base, exponent);
export const round = Math.round;
export const sin = Math.sin;
export const sqrt = Math.sqrt;
export const tan = Math.tan;
